# Generated by Django 4.1.4 on 2022-12-28 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_categoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Category',
        ),
    ]
